application:
  title: CAZ Tariff/Exemption Service

management:
  endpoints:
    web:
      base-path:
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false

swagger:
  api:
    title: Tariff/Exemption Service(API)
    description: Tariffs, charging rules and exemptions of all Clean Air Zones
    version: 0.1

  operations:
    cleanAirZones:
      description: Array containing Clean Air Zone (CAZ) detail objects
    tariff:
      description: Details about Tariff
    db:
      migration:
        description: Evolve DB schema

  model.descriptions:
    cleanAirZones:
      cleanAirZoneDetails: List of Clean Air Zones
    cleanAirZone:
      cleanAirZoneId: ID of the zone
      name: Name of Tariff
      boundaryUrl: URL provided by zone operators, boundary
      exemptionUrl: URL provided by zone operators, exemption
      activeChargeStartDate: ISO-8601 formatted date of when CAZ has effectively started to charge
    tariff:
      cleanAirZoneId: ID of the zone
      name: Name of Tariff
      traiffClass: Tariff Class
      chargeIdentifier: Charge Identifier
      rates: Rates
      informationUrls: URLs information
      chargingDisabledVehicles: Indicates if vehicles with 'DISABLED' tax class are chargeable under this tariff
      activeChargeStartDate: ISO-8601 formatted date of when CAZ has effectively started to charge
    informationUrl:
      mainInfoUrl: URL provided by zone operators, clean air zone
      exemptionOrDiscountUrl: URL provided by zone operators, exemption or discount
      becomeCompliantUrl: URL provided by zone operators, become compliant
      boundaryUrl: URL provided by zone operators, boundary
      additionalInfoUrl: URL provided by zone operators, additional info
      publicTransportOptionsUrl: URL provided by zone operators, public transport options
    rate:
      bus: Price for bus
      coach: Price for coach
      taxi: Price for taxi
      phv: Price for phv
      hgv: Price for hgv
      miniBus: Price for miniBus
      van: Price for van
      car: Price for car
      motorcycle: Price for motorcycle
      moped: Price for moped

spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tariffs
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 1
      connection-timeout: 5000 # in ms
      max-lifetime: 0 # always keep the connection in the pool unless it has been closed

springfox:
  documentation:
    swagger:
      v2:
        path: /v1/swagger-docs