version: '3.3'

services:
  postgres:
    build: ./postgres-with-pgaudit
    image: postgres-pgaudit-local:1
    container_name: postgres.docker
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tariffs

  sonarqube:
    image: sonarqube
    container_name: sonarqube.docker
    ports:
      - 9000:9000
