CREATE ROLE tariffs_readonly_role WITH
NOLOGIN
NOSUPERUSER
NOINHERIT
NOCREATEDB
NOCREATEROLE
NOREPLICATION;

GRANT CONNECT ON DATABASE tariffs TO tariffs_readonly_role;

GRANT USAGE ON SCHEMA public TO tariffs_readonly_role;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO tariffs_readonly_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO tariffs_readonly_role;

GRANT USAGE ON SCHEMA audit TO tariffs_readonly_role;
GRANT SELECT ON ALL TABLES IN SCHEMA audit TO tariffs_readonly_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT ON TABLES TO tariffs_readonly_role;


CREATE ROLE tariffs_readwrite_role WITH
NOLOGIN
NOSUPERUSER
NOINHERIT
NOCREATEDB
NOCREATEROLE
NOREPLICATION;

GRANT CONNECT ON DATABASE tariffs TO tariffs_readwrite_role;

GRANT USAGE ON SCHEMA public TO tariffs_readwrite_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO tariffs_readwrite_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO tariffs_readwrite_role;

GRANT USAGE ON SCHEMA audit TO tariffs_readwrite_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA audit TO tariffs_readwrite_role;
ALTER DEFAULT PRIVILEGES IN SCHEMA audit GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO tariffs_readwrite_role;