### Integration tests configuration

spring:
  datasource:
    url: jdbc:postgresql://${postgres.url:localhost:9999}/caz-tariff
    hikari:
      maximum-pool-size: 10

aws:
  s3:
    endpoint: http://${aws.s3.url:localhost:4572} 